package com.example.sprestdatabase;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

//To tell spring that Product.java is an entry Table, we need to add a @Entity annotation to the class.
@Entity
public class Product {
	//@Table(name = “Product")--> if your table name is different from the class name
	//@Column(name = "price")--->if the field name is different from the field name
	//To tell Spring that id is a primary key, we put the annotation @Id to the field.
	@Id
	//tells Spring that the field is auto-generated and will not be provided by the user,
    //rather, it will be generated by the database.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;	
	private String name;
	private float price;
	private String description;
	private int quantity;
	//private int supplier_id;
	
	public Product()
	{
		
	}
	
	public Product(String name, float price, String description, int quantity) {
		this.name = name;
		this.price = price;
		this.description = description;
		this.quantity = quantity;
	}

	public Product(int id, String name, float price, String description, int quantity) {
		this.id = id;
		this.name = name;
		this.price = price;
		this.description = description;
		this.quantity = quantity;
		//this.supplier_id = supplier_id;
	}
	
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public float getPrice() {
		return price;
	}
	public void setPrice(float price) {
		this.price = price;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public int getQuantity() {
		return quantity;
	}
	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}
	
	@Override
	public String toString() {
		return "Product [id=" + id + ", name=" + name + ", price=" + price + ", description=" + description
				+ ", quantity=" + quantity + "]";
	}
	
	

}
